### ISSUE TITLE
New-SystemData -ComputerName @('FS1') generates system data for more than what's specified

### ISSUE THREAD

**Issue by wwellington2** [microsoft/StigRepo#14]
**Bug/Issue Description**
Provide a clear and concise description the bug/issue

New-SystemData -ComputerName @('FS1') generates system data for more than what's specified. In my test case this will generate system data for all members servers (I only have 2 in my lab)

**Reproduction Steps**
1. New-SystemData -ComputerName @('FS1')
2. New-SystemData -ComputerName 'FS1'

**Expected Behavior**
New-SystemData -ComputerName @('FS1') should only generate system data for the server listed

**Recommended fix action**
If applicable, provide recommendations for how the bug/issue should be remediated

**Existing Workarounds**
If applicable, provide any existing workarounds for the bug/issue

**Screenshots**
![server](https://user-images.githubusercontent.com/41164588/123873056-808c4780-d8fb-11eb-8b14-349e793c483a.PNG)

**Additional context**

**Comment by JakeDean3631** [comment]
Issue closed in version 1.4
