### ISSUE TITLE
MOF not generated after running New-SystemData 

### ISSUE THREAD

**Issue by coaldric** [microsoft/StigRepo#15]
**Bug/Issue Description**
New-SystemData/ActiveDirectoryFunctions - Issue: In some cases, a meta mof will be generated but a mof is not. This is due to get-applicablestigs failing during new-systemdata so the data generated is incomplete. The fix is to make sure WMI Firewall rules are enabled on the remote systems, otherwise the WMI query will fail. 

**Reproduction Steps**
1. Run New-SystemData
2. Run Get-ApplicableSTIGs
3. MetaMof created; Mof not created

**Comment by JakeDean3631** [comment]
This is not a bug being that WinRM connectivity and proper permissions are prerequisites to using StigRepo to manage STIG Compliance. There is not an automated way to fix WinRM connectivity remotely, so this has to be viewed and understood as a prerequisite to using StigRepo.
