### ISSUE TITLE
PowerSTIG_WindowsDNSServer configuration has a static variable for $OSVersion = "2012R2"

### ISSUE THREAD

**Issue by coaldric** [microsoft/StigRepo#16]
PowerSTIG_WindowsDNSServer configuration has a static variable for $OSVersion = "2012R2" in the first section of the config file. @JakeDean101 what's this doing?

**Comment by JakeDean3631** [comment]
This is an issue with the WindowsDNSServer DSC resource in PowerSTIG which only accepts "2012R2" as the OS version currently.
