### ISSUE TITLE
Start-DSCBuild causes PoSH (ISE, CLI) to crash

### ISSUE THREAD

**Issue by coaldric** [microsoft/StigRepo#17]
Start-DSCBuild - Issue: If you run this command after running New-SystemData, but New-SystemData didn't generate any data (just states that it found member servers, but isn't able to connect to them and thus no data is generated) then PoSH will immediately hard crash. This happens in both ISE and PoSH native. 

1. New-SystemData, runs but doesn't generate data
2. Start-DSCBuild
3. Crash

**Comment by JakeDean3631** [comment]
Issue closed in version 1.4
