### ISSUE TITLE
Initialize-StigRepo should create the repo in a standardized place or ask the user

### ISSUE THREAD

**Issue by coaldric** [microsoft/StigRepo#18]
Initialize-StigRepo - Issue: If user doesn't specificy parameters and simply runs initialize-stigrepo, it'll create the repo (4 new folders) in whatever location they were in when they ran the command. This should instead default to a static location or warn the user "Do you want to create the repo in the following location: "C:\user\username" y/n

**Comment by wwellington2** [comment]
@coaldric 

https://github.com/microsoft/StigRepo/tree/Issue-18-Ask-User-Folder-Path

**Comment by JakeDean3631** [comment]
Issue closed in version 1.4
