### ISSUE TITLE
Java detection method is looking for "OracleJRE" as the displayname for a application in the Installed Applications List.  The displayname does not have "OracleJRE " in it. It has the word "Java".  

### ISSUE THREAD

**Issue by bwwillis** [microsoft/StigRepo#27]
**Bug/Issue Description**
Provide a clear and concise description the bug/issue
Java detection method is looking for "OracleJRE" as the displayname for a application in the Installed Applications List.  The displayname does not have "OracleJRE " in it.  It has the word "Java".  
**Reproduction Steps**
1. 
2. 
3. 

**Expected Behavior**
A clear and concise description of what you expected to happen
The tool should be able to detect the OracleJRE installed version correctly.

**Recommended fix action**
If applicable, provide recommendations for how the bug/issue should be remediated
Can we change the detection to be based on the registry keys ?
For 64bit and 32bit versions installed.

HKLM
|
-> SOFTWARE
                |
                |-> JavaSoft
                                |-> Java Runtime Environment
                                                |-> CurrentVersion = 1.8
                |
                |-> Wow6432Node
                                |-> Java Runtime Environment
                                                |-> CurrentVersion = 1.7

**Existing Workarounds**
If applicable, provide any existing workarounds for the bug/issue

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**

**Comment by wwellington2** [comment]
Issure resolved in JavaDetectionIssue_#27 PR
