### ISSUE TITLE
Adobe DC detection does not discern between Reader and Pro versions.

### ISSUE THREAD

**Issue by bwwillis** [microsoft/StigRepo#29]
**Bug/Issue Description**
Provide a clear and concise description the bug/issue
My customer is deploying Adobe DC Continuous to workstations with the Pro entitlement.  The detection method uses the Installed Software List nad the DisplayName -Like "*Adobe*".  This will not discern between the Reader and Pro versions which have separate STIGs/vulnerabilities.  
Adobe DCPro is not currently supported by PowerSTIG but there is feature request submitted and it is anticipated with the next release or soon after.

**Reproduction Steps**
1. 
2. 
3. 

**Expected Behavior**
A clear and concise description of what you expected to happen

**Recommended fix action**
If applicable, provide recommendations for how the bug/issue should be remediated

The correct detection is noted in the following:
https://www.adobe.com/devnet-docs/acrobatetk/tools/AdminGuide/identify.html

I am using the following registry key to identify the Reader vs Pro installs:
64-bit Acrobat Pro vs. Standard
Both the LEID & SWID tag identification methods are not applicable to the Acrobat 64-bit unified installer iniitially released in Feb. of 2021. To distinguish between Standard and Pro installations, ID the install via the registry:
#. Go to Computer\HKEY_CURRENT_USER\Software\Adobe\Adobe Acrobat\DC\AVEntitlement\iEntitlementLevel # ID the install:
• 300: Acrobat Pro
• 200: Acrobat Standard

**Existing Workarounds**
If applicable, provide any existing workarounds for the bug/issue
Completely manual checklist for dbobe DC Pro.
**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**

**Comment by wwellington2** [comment]
Resolved in Adobe-Detection-issue-#29 PR
