### ISSUE TITLE
Possible issue in StigRepo 1.2 with finding manual checks for DC WinDnsServer and WinClient STIGs

### ISSUE THREAD

**Issue by wwellington2** [microsoft/StigRepo#5]
Possible issue in StigRepo 1.2 with finding manual checks for DC, WinDnsServer and WinClient STIGs when running New-SystemData

![ManualCheck](https://user-images.githubusercontent.com/41164588/121726334-044ad500-cab0-11eb-9278-a83eea091e68.PNG)
![ManualCheck2](https://user-images.githubusercontent.com/41164588/121726336-057c0200-cab0-11eb-95e1-0fe4091981ca.PNG)

**Comment by JakeDean3631** [comment]
Issue #5 resolved in StigRepo 1.3 release
